"""core geo tables and zylo_liquid layers 1-2

Revision ID: 0240c128e5de
Revises: da0ccc1f6d2c
Create Date: 2026-09-01 04:57:01.687184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0240c128e5de'
down_revision: Union[str, None] = 'da0ccc1f6d2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('isoCode2', sa.String(length=2), nullable=False),
    sa.Column('isoCode3', sa.String(length=3), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('currencyCode', sa.String(length=3), nullable=False),
    sa.Column('currencySymbol', sa.String(length=10), nullable=False),
    sa.Column('phonePrefix', sa.String(length=6), nullable=True),
    sa.Column('defaultTimezone', sa.String(length=50), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('"isoCode2" = upper("isoCode2")', name='ck_country_isoCode2_upper'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isoCode2', name='uq_country_isoCode2'),
    comment="Référentiel des pays — commun à tous les modules (Core). Source : table 'pays' de la base zylo_liquid réelle, absente du schéma initial validé."
    )
    op.create_table('zyloLiquidFuelProduct',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('densityGPerCm3', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('currentPriceFcfa', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currentCostFcfa', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('displayColor', sa.String(length=7), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    comment="Référentiel des carburants et leurs propriétés physiques/financières. Source : table 'fuel_products'."
    )
    op.create_table('region',
    sa.Column('countryId', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['countryId'], ['country.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('countryId', 'name', name='uq_region_country_name'),
    comment="Découpage administratif régional d'un pays (Core). Source : table 'regions' de la base zylo_liquid réelle."
    )
    op.create_index(op.f('ix_region_countryId'), 'region', ['countryId'], unique=False)
    op.create_table('zyloLiquidHolykellAccount',
    sa.Column('organizationId', sa.UUID(), nullable=False),
    sa.Column('holykellUsername', sa.String(length=100), nullable=False),
    sa.Column('holykellPassword', sa.String(length=255), nullable=False),
    sa.Column('holykellTenantId', sa.String(length=50), nullable=True),
    sa.Column('accessToken', sa.Text(), nullable=True),
    sa.Column('refreshToken', sa.Text(), nullable=True),
    sa.Column('tokenExpiresAt', sa.DateTime(), nullable=True),
    sa.Column('lastSyncAt', sa.DateTime(), nullable=True),
    sa.Column('lastSyncStatus', sa.String(length=10), nullable=True),
    sa.Column('lastSyncError', sa.Text(), nullable=True),
    sa.Column('syncEnabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('"lastSyncStatus" IN (\'success\',\'partial\',\'failed\')', name='ck_zlHolykellAccount_syncStatus'),
    sa.ForeignKeyConstraint(['organizationId'], ['organization.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    comment="Credentials et état de synchronisation d'un compte Holykell (h-smartlink.com) lié à une organisation Zylo Office. Source : table 'holykell_accounts'."
    )
    op.create_index(op.f('ix_zyloLiquidHolykellAccount_organizationId'), 'zyloLiquidHolykellAccount', ['organizationId'], unique=False)
    op.create_table('city',
    sa.Column('regionId', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['regionId'], ['region.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('regionId', 'name', name='uq_city_region_name'),
    comment="Ville rattachée à une région (Core). Source : table 'villes' de la base zylo_liquid réelle."
    )
    op.create_index(op.f('ix_city_regionId'), 'city', ['regionId'], unique=False)
    op.create_table('zyloLiquidHolykellDeviceRegistry',
    sa.Column('holykellAccountId', sa.UUID(), nullable=False),
    sa.Column('hkGroupId', sa.Integer(), nullable=False),
    sa.Column('hkGroupName', sa.String(length=200), nullable=False),
    sa.Column('hkDeviceId', sa.Integer(), nullable=False),
    sa.Column('hkDeviceName', sa.String(length=200), nullable=True),
    sa.Column('hkSerialNumber', sa.String(length=100), nullable=False),
    sa.Column('hkProtocol', sa.String(length=50), nullable=True),
    sa.Column('hkReportCycleSec', sa.Integer(), nullable=True),
    sa.Column('hkLatitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('hkLongitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('hkLastStatus', sa.SmallInteger(), nullable=True),
    sa.Column('hkLastSeenAt', sa.DateTime(), nullable=True),
    sa.Column('hkSensorId', sa.Integer(), nullable=False),
    sa.Column('hkSensorName', sa.String(length=200), nullable=True),
    sa.Column('hkReadWriteMark', sa.String(length=50), nullable=True),
    sa.Column('hkUnit', sa.String(length=20), nullable=True),
    sa.Column('hkSensorType', sa.SmallInteger(), nullable=True),
    sa.Column('hkDecimalPlaces', sa.SmallInteger(), nullable=True),
    sa.Column('sensorCategory', sa.String(length=10), nullable=False),
    sa.Column('isMapped', sa.Boolean(), nullable=False),
    sa.Column('mappedAt', sa.DateTime(), nullable=True),
    sa.Column('lastValue', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('lastValueAt', sa.DateTime(), nullable=True),
    sa.Column('syncFrom', sa.DateTime(), nullable=False),
    sa.Column('discoveredAt', sa.DateTime(), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('rawDevicePayload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('"hkLastStatus" IN (0,1)', name='ck_zlHolykellDevice_lastStatus'),
    sa.CheckConstraint('"sensorCategory" IN (\'physical\',\'device\')', name='ck_zlHolykellDevice_sensorCategory'),
    sa.ForeignKeyConstraint(['holykellAccountId'], ['zyloLiquidHolykellAccount.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hkSensorId', name='uq_zlHolykellDevice_hkSensorId_global'),
    sa.UniqueConstraint('holykellAccountId', 'hkSensorId', name='uq_zlHolykellDevice_account_sensor'),
    comment="Registre de tous les sensors Holykell (device HK301 + sensor dénormalisés sur une seule ligne pour le chemin critique de synchronisation). Source : table 'holykell_devices_registry'."
    )
    op.create_index(op.f('ix_zyloLiquidHolykellDeviceRegistry_hkSensorId'), 'zyloLiquidHolykellDeviceRegistry', ['hkSensorId'], unique=False)
    op.create_index(op.f('ix_zyloLiquidHolykellDeviceRegistry_hkSerialNumber'), 'zyloLiquidHolykellDeviceRegistry', ['hkSerialNumber'], unique=False)
    op.create_index(op.f('ix_zyloLiquidHolykellDeviceRegistry_holykellAccountId'), 'zyloLiquidHolykellDeviceRegistry', ['holykellAccountId'], unique=False)
    op.create_table('zyloLiquidStation',
    sa.Column('organizationId', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('cityId', sa.UUID(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('holykellGroupId', sa.Integer(), nullable=True),
    sa.Column('openingTime', sa.String(length=8), nullable=False),
    sa.Column('closingTime', sa.String(length=8), nullable=False),
    sa.Column('is24h', sa.Boolean(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('integrationDate', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('exploitationType', sa.String(length=20), nullable=False),
    sa.Column('hasShop', sa.Boolean(), nullable=False),
    sa.Column('shopName', sa.String(length=120), nullable=True),
    sa.Column('shopSurfaceM2', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('hasLavage', sa.Boolean(), nullable=False),
    sa.Column('hasVidange', sa.Boolean(), nullable=False),
    sa.Column('hasGazDomestique', sa.Boolean(), nullable=False),
    sa.Column('nbPistes', sa.SmallInteger(), nullable=True),
    sa.Column('surfaceTotaleM2', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active','maintenance','inactive')", name='ck_zlStation_status'),
    sa.ForeignKeyConstraint(['cityId'], ['city.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organizationId'], ['organization.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organizationId', 'code', name='uq_zlStation_org_code'),
    comment="Station-service physique appartenant à une organisation. Rattachements géographiques (cityId) alignés sur la base réelle testée, plus riche que le schéma initial (city/region en texte libre) — voir phase-1-database.md §5. Source : table 'stations'."
    )
    op.create_index(op.f('ix_zyloLiquidStation_cityId'), 'zyloLiquidStation', ['cityId'], unique=False)
    op.create_index(op.f('ix_zyloLiquidStation_organizationId'), 'zyloLiquidStation', ['organizationId'], unique=False)
    op.create_table('zyloLiquidTankMeasurement',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hkMeasurementId', sa.String(length=50), nullable=True),
    sa.Column('hkSensorId', sa.Integer(), nullable=False),
    sa.Column('hkDeviceSerial', sa.String(length=100), nullable=False),
    sa.Column('hkSensorName', sa.String(length=200), nullable=True),
    sa.Column('hkReadWriteMark', sa.String(length=50), nullable=True),
    sa.Column('hkUnit', sa.String(length=20), nullable=True),
    sa.Column('hkDecimalPlaces', sa.SmallInteger(), nullable=True),
    sa.Column('measuredAt', sa.DateTime(), nullable=False),
    sa.Column('receivedAt', sa.DateTime(), nullable=True),
    sa.Column('networkDelaySec', sa.Integer(), nullable=True),
    sa.Column('rawValue', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('insertedAt', sa.DateTime(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('isCorrection', sa.Boolean(), nullable=False),
    sa.Column('correctsMeasurementId', sa.Integer(), nullable=True),
    sa.Column('rawHolykellResponse', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['hkSensorId'], ['zyloLiquidHolykellDeviceRegistry.hkSensorId'], ),
    sa.PrimaryKeyConstraint('id'),
    comment="Journal immuable des mesures physiques reçues depuis Holykell — jamais converties, jamais modifiées. Partitionnée par mois (measuredAt) dans le schéma source. Source : table 'tank_measurements'."
    )
    op.create_index(op.f('ix_zyloLiquidTankMeasurement_hkMeasurementId'), 'zyloLiquidTankMeasurement', ['hkMeasurementId'], unique=False)
    op.create_index(op.f('ix_zyloLiquidTankMeasurement_hkSensorId'), 'zyloLiquidTankMeasurement', ['hkSensorId'], unique=False)
    op.create_index(op.f('ix_zyloLiquidTankMeasurement_measuredAt'), 'zyloLiquidTankMeasurement', ['measuredAt'], unique=False)
    op.create_table('zyloLiquidTank',
    sa.Column('stationId', sa.UUID(), nullable=False),
    sa.Column('fuelProductId', sa.UUID(), nullable=False),
    sa.Column('tankNumber', sa.SmallInteger(), nullable=False),
    sa.Column('displayName', sa.String(length=100), nullable=False),
    sa.Column('capacityLiters', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('calibratedCapacityLiters', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tankHeightMm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('dataSourceType', sa.String(length=10), nullable=False),
    sa.Column('alertLowPercent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('alertCriticalPercent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('alertHighPercent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('alertWaterMaxMm', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('productSince', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('"capacityLiters" > 0', name='ck_zlTank_capacity_positive'),
    sa.CheckConstraint('"dataSourceType" IN (\'console\',\'direct\')', name='ck_zlTank_dataSourceType'),
    sa.ForeignKeyConstraint(['fuelProductId'], ['zyloLiquidFuelProduct.id'], ),
    sa.ForeignKeyConstraint(['stationId'], ['zyloLiquidStation.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stationId', 'tankNumber', name='uq_zlTank_station_number'),
    comment="Cuve physique installée dans une station. Source : table 'tanks'."
    )
    op.create_index(op.f('ix_zyloLiquidTank_fuelProductId'), 'zyloLiquidTank', ['fuelProductId'], unique=False)
    op.create_index(op.f('ix_zyloLiquidTank_stationId'), 'zyloLiquidTank', ['stationId'], unique=False)
    op.create_table('zyloLiquidTankCalibrationPoint',
    sa.Column('tankId', sa.UUID(), nullable=False),
    sa.Column('heightMm', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('volumeLiters', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tankId'], ['zyloLiquidTank.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tankId', 'heightMm', name='uq_zlTankCalibrationPoint_tank_height'),
    comment="Point de calibration (hauteur mm -> volume litres) d'une cuve. Interpolation linéaire appliquée en Phase 2 (algorithme, hors périmètre de cette phase). Source : table 'tank_calibration_points'."
    )
    op.create_index(op.f('ix_zyloLiquidTankCalibrationPoint_tankId'), 'zyloLiquidTankCalibrationPoint', ['tankId'], unique=False)
    op.create_table('zyloLiquidTankSensorMapping',
    sa.Column('hkSensorId', sa.Integer(), nullable=False),
    sa.Column('tankId', sa.UUID(), nullable=False),
    sa.Column('measurementType', sa.String(length=20), nullable=False),
    sa.Column('validFrom', sa.DateTime(), nullable=False),
    sa.Column('validUntil', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('"measurementType" IN (\'product_level\',\'water_level\',\'temperature\')', name='ck_zlTankSensorMapping_measurementType'),
    sa.ForeignKeyConstraint(['hkSensorId'], ['zyloLiquidHolykellDeviceRegistry.hkSensorId'], ),
    sa.ForeignKeyConstraint(['tankId'], ['zyloLiquidTank.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hkSensorId', 'measurementType', 'tankId', name='uq_zlTankSensorMapping_sensor_type_tank'),
    comment="Pont entre un sensor Holykell (couche télémétrie) et une cuve Zylo Liquid (couche référentiel). Source : table 'tank_sensor_mapping'."
    )
    op.create_index(op.f('ix_zyloLiquidTankSensorMapping_hkSensorId'), 'zyloLiquidTankSensorMapping', ['hkSensorId'], unique=False)
    op.create_index(op.f('ix_zyloLiquidTankSensorMapping_tankId'), 'zyloLiquidTankSensorMapping', ['tankId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zyloLiquidTankSensorMapping_tankId'), table_name='zyloLiquidTankSensorMapping')
    op.drop_index(op.f('ix_zyloLiquidTankSensorMapping_hkSensorId'), table_name='zyloLiquidTankSensorMapping')
    op.drop_table('zyloLiquidTankSensorMapping')
    op.drop_index(op.f('ix_zyloLiquidTankCalibrationPoint_tankId'), table_name='zyloLiquidTankCalibrationPoint')
    op.drop_table('zyloLiquidTankCalibrationPoint')
    op.drop_index(op.f('ix_zyloLiquidTank_stationId'), table_name='zyloLiquidTank')
    op.drop_index(op.f('ix_zyloLiquidTank_fuelProductId'), table_name='zyloLiquidTank')
    op.drop_table('zyloLiquidTank')
    op.drop_index(op.f('ix_zyloLiquidTankMeasurement_measuredAt'), table_name='zyloLiquidTankMeasurement')
    op.drop_index(op.f('ix_zyloLiquidTankMeasurement_hkSensorId'), table_name='zyloLiquidTankMeasurement')
    op.drop_index(op.f('ix_zyloLiquidTankMeasurement_hkMeasurementId'), table_name='zyloLiquidTankMeasurement')
    op.drop_table('zyloLiquidTankMeasurement')
    op.drop_index(op.f('ix_zyloLiquidStation_organizationId'), table_name='zyloLiquidStation')
    op.drop_index(op.f('ix_zyloLiquidStation_cityId'), table_name='zyloLiquidStation')
    op.drop_table('zyloLiquidStation')
    op.drop_index(op.f('ix_zyloLiquidHolykellDeviceRegistry_holykellAccountId'), table_name='zyloLiquidHolykellDeviceRegistry')
    op.drop_index(op.f('ix_zyloLiquidHolykellDeviceRegistry_hkSerialNumber'), table_name='zyloLiquidHolykellDeviceRegistry')
    op.drop_index(op.f('ix_zyloLiquidHolykellDeviceRegistry_hkSensorId'), table_name='zyloLiquidHolykellDeviceRegistry')
    op.drop_table('zyloLiquidHolykellDeviceRegistry')
    op.drop_index(op.f('ix_city_regionId'), table_name='city')
    op.drop_table('city')
    op.drop_index(op.f('ix_zyloLiquidHolykellAccount_organizationId'), table_name='zyloLiquidHolykellAccount')
    op.drop_table('zyloLiquidHolykellAccount')
    op.drop_index(op.f('ix_region_countryId'), table_name='region')
    op.drop_table('region')
    op.drop_table('zyloLiquidFuelProduct')
    op.drop_table('country')
    # ### end Alembic commands ###
