"""modules registry tables

Revision ID: 1ede243704c7
Revises: 4b1cccdb5fd5
Create Date: 2026-08-31 17:30:26.416581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ede243704c7'
down_revision: Union[str, None] = '4b1cccdb5fd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('module',
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='Registre statique des modules connus du système (CRM, Stock, zylo_liquid...).'
    )
    op.create_index(op.f('ix_module_code'), 'module', ['code'], unique=True)
    op.create_table('organizationModule',
    sa.Column('organizationId', sa.UUID(), nullable=False),
    sa.Column('moduleCode', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('activatedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deactivatedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['moduleCode'], ['module.code'], ),
    sa.ForeignKeyConstraint(['organizationId'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organizationId', 'moduleCode', name='uq_organizationModule_org_module'),
    comment="État d'activation d'un module pour une organisation donnée (active/inactive/trial)."
    )
    op.create_index(op.f('ix_organizationModule_moduleCode'), 'organizationModule', ['moduleCode'], unique=False)
    op.create_index(op.f('ix_organizationModule_organizationId'), 'organizationModule', ['organizationId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organizationModule_organizationId'), table_name='organizationModule')
    op.drop_index(op.f('ix_organizationModule_moduleCode'), table_name='organizationModule')
    op.drop_table('organizationModule')
    op.drop_index(op.f('ix_module_code'), table_name='module')
    op.drop_table('module')
    # ### end Alembic commands ###
