"""identity, rbac and auth tables

Revision ID: 4b1cccdb5fd5
Revises: ab0ecf05c6ca
Create Date: 2026-08-31 17:17:54.083234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b1cccdb5fd5'
down_revision: Union[str, None] = 'ab0ecf05c6ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deletedAt', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    comment='Organisation cliente de Zylo Office — tenant racine du système multi-organisation.'
    )
    op.create_table('permission',
    sa.Column('code', sa.String(length=150), nullable=False),
    sa.Column('moduleCode', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='Permission globale au système, déclarée par un module (convention: module.resource.action).'
    )
    op.create_index(op.f('ix_permission_code'), 'permission', ['code'], unique=True)
    op.create_index(op.f('ix_permission_moduleCode'), 'permission', ['moduleCode'], unique=False)
    op.create_table('user',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashedPassword', sa.String(length=255), nullable=False),
    sa.Column('fullName', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deletedAt', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='Utilisateur du système — identité unique, valable pour toutes les organisations et tous les modules.'
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('organizationUser',
    sa.Column('organizationId', sa.UUID(), nullable=False),
    sa.Column('userId', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organizationId'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organizationId', 'userId', name='uq_organizationUser_org_user'),
    comment='Association utilisateur <-> organisation (appartenance, many-to-many).'
    )
    op.create_index(op.f('ix_organizationUser_organizationId'), 'organizationUser', ['organizationId'], unique=False)
    op.create_index(op.f('ix_organizationUser_userId'), 'organizationUser', ['userId'], unique=False)
    op.create_table('refreshToken',
    sa.Column('userId', sa.UUID(), nullable=False),
    sa.Column('tokenHash', sa.String(length=255), nullable=False),
    sa.Column('expiresAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revokedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tokenHash'),
    comment='Refresh token JWT émis à un utilisateur — révocable individuellement, avec rotation à chaque renouvellement.'
    )
    op.create_index(op.f('ix_refreshToken_userId'), 'refreshToken', ['userId'], unique=False)
    op.create_table('role',
    sa.Column('organizationId', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organizationId'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organizationId', 'code', name='uq_role_org_code'),
    comment='Rôle métier scopé à une organisation (ex: Admin, Comptable).'
    )
    op.create_index(op.f('ix_role_organizationId'), 'role', ['organizationId'], unique=False)
    op.create_table('rolePermission',
    sa.Column('roleId', sa.UUID(), nullable=False),
    sa.Column('permissionId', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['permissionId'], ['permission.id'], ),
    sa.ForeignKeyConstraint(['roleId'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('roleId', 'permissionId', name='uq_rolePermission_role_perm'),
    comment='Association rôle <-> permission (many-to-many).'
    )
    op.create_index(op.f('ix_rolePermission_permissionId'), 'rolePermission', ['permissionId'], unique=False)
    op.create_index(op.f('ix_rolePermission_roleId'), 'rolePermission', ['roleId'], unique=False)
    op.create_table('userRole',
    sa.Column('userId', sa.UUID(), nullable=False),
    sa.Column('organizationId', sa.UUID(), nullable=False),
    sa.Column('roleId', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organizationId'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['roleId'], ['role.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userId', 'organizationId', 'roleId', name='uq_userRole_user_org_role'),
    comment="Attribution d'un rôle à un utilisateur, scopée à une organisation (un même user peut avoir un rôle différent selon l'organisation)."
    )
    op.create_index(op.f('ix_userRole_organizationId'), 'userRole', ['organizationId'], unique=False)
    op.create_index(op.f('ix_userRole_roleId'), 'userRole', ['roleId'], unique=False)
    op.create_index(op.f('ix_userRole_userId'), 'userRole', ['userId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_userRole_userId'), table_name='userRole')
    op.drop_index(op.f('ix_userRole_roleId'), table_name='userRole')
    op.drop_index(op.f('ix_userRole_organizationId'), table_name='userRole')
    op.drop_table('userRole')
    op.drop_index(op.f('ix_rolePermission_roleId'), table_name='rolePermission')
    op.drop_index(op.f('ix_rolePermission_permissionId'), table_name='rolePermission')
    op.drop_table('rolePermission')
    op.drop_index(op.f('ix_role_organizationId'), table_name='role')
    op.drop_table('role')
    op.drop_index(op.f('ix_refreshToken_userId'), table_name='refreshToken')
    op.drop_table('refreshToken')
    op.drop_index(op.f('ix_organizationUser_userId'), table_name='organizationUser')
    op.drop_index(op.f('ix_organizationUser_organizationId'), table_name='organizationUser')
    op.drop_table('organizationUser')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_permission_moduleCode'), table_name='permission')
    op.drop_index(op.f('ix_permission_code'), table_name='permission')
    op.drop_table('permission')
    op.drop_table('organization')
    # ### end Alembic commands ###
