"""fuel_product_organization_id

Revision ID: 7ffb9473d45e
Revises: 0240c128e5de
Create Date: 2026-09-01 09:33:58.899278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ffb9473d45e'
down_revision: Union[str, None] = '0240c128e5de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Données de développement antérieures à la décision d'isolation multi-tenant
    # (endpoint 1, Point 3 §9.3) : aucune ligne de production concernée, purge
    # nécessaire pour permettre l'ajout de la colonne NOT NULL.
    op.execute('TRUNCATE TABLE "zyloLiquidFuelProduct" CASCADE')
    op.add_column('zyloLiquidFuelProduct', sa.Column('organizationId', sa.UUID(), nullable=False))
    op.drop_constraint('zyloLiquidFuelProduct_code_key', 'zyloLiquidFuelProduct', type_='unique')
    op.create_index(op.f('ix_zyloLiquidFuelProduct_organizationId'), 'zyloLiquidFuelProduct', ['organizationId'], unique=False)
    op.create_unique_constraint('uq_zlFuelProduct_org_code', 'zyloLiquidFuelProduct', ['organizationId', 'code'])
    op.create_foreign_key(None, 'zyloLiquidFuelProduct', 'organization', ['organizationId'], ['id'], ondelete='RESTRICT')
    op.create_table_comment(
        'zyloLiquidFuelProduct',
        "Référentiel des carburants et leurs propriétés physiques/financières. Source : table 'fuel_products'. organizationId ajouté à la construction de l'endpoint 1 (Point 3 §9.3) : absent du schéma source et de la base réelle (réseau unique testé), mais requis par cohérence avec l'isolation multi-tenant de toutes les autres tables Zylo Liquid (Station, Tank...) — sans cette colonne, une organisation verrait/modifierait le référentiel carburant d'une autre. Le code redevient unique par organisation, plus globalement.",
        existing_comment="Référentiel des carburants et leurs propriétés physiques/financières. Source : table 'fuel_products'.",
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'zyloLiquidFuelProduct',
        "Référentiel des carburants et leurs propriétés physiques/financières. Source : table 'fuel_products'.",
        existing_comment="Référentiel des carburants et leurs propriétés physiques/financières. Source : table 'fuel_products'. organizationId ajouté à la construction de l'endpoint 1 (Point 3 §9.3) : absent du schéma source et de la base réelle (réseau unique testé), mais requis par cohérence avec l'isolation multi-tenant de toutes les autres tables Zylo Liquid (Station, Tank...) — sans cette colonne, une organisation verrait/modifierait le référentiel carburant d'une autre. Le code redevient unique par organisation, plus globalement.",
        schema=None
    )
    op.drop_constraint(None, 'zyloLiquidFuelProduct', type_='foreignkey')
    op.drop_constraint('uq_zlFuelProduct_org_code', 'zyloLiquidFuelProduct', type_='unique')
    op.drop_index(op.f('ix_zyloLiquidFuelProduct_organizationId'), table_name='zyloLiquidFuelProduct')
    op.create_unique_constraint('zyloLiquidFuelProduct_code_key', 'zyloLiquidFuelProduct', ['code'])
    op.drop_column('zyloLiquidFuelProduct', 'organizationId')
    # ### end Alembic commands ###
