"""tank_mm_alarm_thresholds

Revision ID: 82fd37bd908f
Revises: 7ffb9473d45e
Create Date: 2026-09-01 10:12:23.561872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82fd37bd908f'
down_revision: Union[str, None] = '7ffb9473d45e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zyloLiquidTank', sa.Column('heightAlarmMm', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('zyloLiquidTank', sa.Column('heightAlertMm', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('zyloLiquidTank', sa.Column('lowAlarmMm', sa.Numeric(precision=10, scale=2), nullable=False))
    op.drop_column('zyloLiquidTank', 'alertLowPercent')
    op.drop_column('zyloLiquidTank', 'alertHighPercent')
    op.drop_column('zyloLiquidTank', 'alertCriticalPercent')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zyloLiquidTank', sa.Column('alertCriticalPercent', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False))
    op.add_column('zyloLiquidTank', sa.Column('alertHighPercent', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False))
    op.add_column('zyloLiquidTank', sa.Column('alertLowPercent', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False))
    op.drop_column('zyloLiquidTank', 'lowAlarmMm')
    op.drop_column('zyloLiquidTank', 'heightAlertMm')
    op.drop_column('zyloLiquidTank', 'heightAlarmMm')
    # ### end Alembic commands ###
