"""delivery_detected

Revision ID: 83f1a725f86b
Revises: fecaf414f49e
Create Date: 2026-09-01 11:52:14.684216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83f1a725f86b'
down_revision: Union[str, None] = 'fecaf414f49e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zyloLiquidDeliveryDetected',
    sa.Column('tankId', sa.UUID(), nullable=False),
    sa.Column('startTime', sa.DateTime(), nullable=False),
    sa.Column('startHeightMm', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('startVolumeLiters', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('endTime', sa.DateTime(), nullable=False),
    sa.Column('endHeightMm', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('endVolumeLiters', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('volumeLiters', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tankId'], ['zyloLiquidTank.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tankId', 'startTime', name='uq_zlDeliveryDetected_tank_start'),
    comment="Livraison détectée automatiquement par l'algorithme de Point 8 §8.3 — jamais créée manuellement."
    )
    op.create_index(op.f('ix_zyloLiquidDeliveryDetected_startTime'), 'zyloLiquidDeliveryDetected', ['startTime'], unique=False)
    op.create_index(op.f('ix_zyloLiquidDeliveryDetected_tankId'), 'zyloLiquidDeliveryDetected', ['tankId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zyloLiquidDeliveryDetected_tankId'), table_name='zyloLiquidDeliveryDetected')
    op.drop_index(op.f('ix_zyloLiquidDeliveryDetected_startTime'), table_name='zyloLiquidDeliveryDetected')
    op.drop_table('zyloLiquidDeliveryDetected')
    # ### end Alembic commands ###
