"""user role scoped assignment

Revision ID: 95e8bd6bf477
Revises: d77282efbbb2
Create Date: 2026-09-06 17:57:00.278078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95e8bd6bf477'
down_revision: Union[str, None] = 'd77282efbbb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userRole', sa.Column('resourceType', sa.String(length=100), nullable=True))
    op.add_column('userRole', sa.Column('resourceId', sa.UUID(), nullable=True))
    op.drop_constraint('uq_userRole_user_org_role', 'userRole', type_='unique')
    op.create_unique_constraint('uq_userRole_user_org_role_scope', 'userRole', ['userId', 'organizationId', 'roleId', 'resourceType', 'resourceId'])
    op.create_table_comment(
        'userRole',
        "Attribution d'un rôle à un utilisateur, scopée à une organisation et éventuellement à une ressource précise (station...).",
        existing_comment="Attribution d'un rôle à un utilisateur, scopée à une organisation (un même user peut avoir un rôle différent selon l'organisation).",
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'userRole',
        "Attribution d'un rôle à un utilisateur, scopée à une organisation (un même user peut avoir un rôle différent selon l'organisation).",
        existing_comment="Attribution d'un rôle à un utilisateur, scopée à une organisation et éventuellement à une ressource précise (station...).",
        schema=None
    )
    op.drop_constraint('uq_userRole_user_org_role_scope', 'userRole', type_='unique')
    op.create_unique_constraint('uq_userRole_user_org_role', 'userRole', ['userId', 'organizationId', 'roleId'])
    op.drop_column('userRole', 'resourceId')
    op.drop_column('userRole', 'resourceType')
    # ### end Alembic commands ###
