"""price_history

Revision ID: b41b805c3119
Revises: d631274928c1
Create Date: 2026-09-01 13:11:04.554569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b41b805c3119'
down_revision: Union[str, None] = 'd631274928c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zyloLiquidPriceHistory',
    sa.Column('stationId', sa.UUID(), nullable=False),
    sa.Column('fuelProductId', sa.UUID(), nullable=False),
    sa.Column('currencyId', sa.UUID(), nullable=False),
    sa.Column('priceAmount', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('costAmount', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('effectiveFrom', sa.DateTime(), nullable=False),
    sa.Column('changeReason', sa.Text(), nullable=True),
    sa.Column('createdBy', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('"priceAmount" > 0', name='ck_zlPriceHistory_priceAmount_positive'),
    sa.ForeignKeyConstraint(['createdBy'], ['user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['currencyId'], ['currency.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['fuelProductId'], ['zyloLiquidFuelProduct.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['stationId'], ['zyloLiquidStation.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stationId', 'fuelProductId', 'effectiveFrom', name='uq_zlPriceHistory_station_product_effectiveFrom'),
    comment="Historique des prix — changement réel = insertion, correction = UPDATE ciblé. Source : table 'price_history'."
    )
    op.create_index(op.f('ix_zyloLiquidPriceHistory_effectiveFrom'), 'zyloLiquidPriceHistory', ['effectiveFrom'], unique=False)
    op.create_index(op.f('ix_zyloLiquidPriceHistory_fuelProductId'), 'zyloLiquidPriceHistory', ['fuelProductId'], unique=False)
    op.create_index(op.f('ix_zyloLiquidPriceHistory_stationId'), 'zyloLiquidPriceHistory', ['stationId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zyloLiquidPriceHistory_stationId'), table_name='zyloLiquidPriceHistory')
    op.drop_index(op.f('ix_zyloLiquidPriceHistory_fuelProductId'), table_name='zyloLiquidPriceHistory')
    op.drop_index(op.f('ix_zyloLiquidPriceHistory_effectiveFrom'), table_name='zyloLiquidPriceHistory')
    op.drop_table('zyloLiquidPriceHistory')
    # ### end Alembic commands ###
