"""currency_exchange_rate

Revision ID: d631274928c1
Revises: fb5b32ada7ce
Create Date: 2026-09-01 12:56:18.530404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd631274928c1'
down_revision: Union[str, None] = 'fb5b32ada7ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency',
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('decimalPlaces', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('code = upper(code)', name='ck_currency_code_upper'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_currency_code'),
    comment='Référentiel des devises — commun à tous les modules (Core). Source : niveau_1_base_de_donnees_et_monetisation.md §17.'
    )
    op.create_table('exchangeRate',
    sa.Column('sourceCurrencyId', sa.UUID(), nullable=False),
    sa.Column('targetCurrencyId', sa.UUID(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('effectiveFrom', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('"sourceCurrencyId" != "targetCurrencyId"', name='ck_exchangeRate_distinct_currencies'),
    sa.CheckConstraint('rate > 0', name='ck_exchangeRate_rate_positive'),
    sa.ForeignKeyConstraint(['sourceCurrencyId'], ['currency.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['targetCurrencyId'], ['currency.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sourceCurrencyId', 'targetCurrencyId', 'effectiveFrom', name='uq_exchangeRate_pair_effectiveFrom'),
    comment='Taux de change historisé — toujours une insertion, jamais une correction (niveau_1_base_de_donnees_et_monetisation.md §22, invariant n°4).'
    )
    op.create_index(op.f('ix_exchangeRate_effectiveFrom'), 'exchangeRate', ['effectiveFrom'], unique=False)
    op.create_index(op.f('ix_exchangeRate_sourceCurrencyId'), 'exchangeRate', ['sourceCurrencyId'], unique=False)
    op.create_index(op.f('ix_exchangeRate_targetCurrencyId'), 'exchangeRate', ['targetCurrencyId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exchangeRate_targetCurrencyId'), table_name='exchangeRate')
    op.drop_index(op.f('ix_exchangeRate_sourceCurrencyId'), table_name='exchangeRate')
    op.drop_index(op.f('ix_exchangeRate_effectiveFrom'), table_name='exchangeRate')
    op.drop_table('exchangeRate')
    op.drop_table('currency')
    # ### end Alembic commands ###
