"""user permission grant and audit log

Revision ID: d77282efbbb2
Revises: e6f7a8b9c0d1
Create Date: 2026-09-06 09:35:21.292721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd77282efbbb2'
down_revision: Union[str, None] = 'e6f7a8b9c0d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditLog',
    sa.Column('organizationId', sa.UUID(), nullable=False),
    sa.Column('actorUserId', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=150), nullable=False),
    sa.Column('entityType', sa.String(length=100), nullable=False),
    sa.Column('entityId', sa.UUID(), nullable=True),
    sa.Column('scopeResourceType', sa.String(length=100), nullable=True),
    sa.Column('scopeResourceId', sa.UUID(), nullable=True),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.Column('ipAddress', sa.String(length=64), nullable=True),
    sa.Column('userAgent', sa.String(length=255), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actorUserId'], ['user.id'], ),
    sa.ForeignKeyConstraint(['organizationId'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment="Journal d'audit — qui a fait quoi, sur quel élément, quand."
    )
    op.create_index(op.f('ix_auditLog_action'), 'auditLog', ['action'], unique=False)
    op.create_index(op.f('ix_auditLog_actorUserId'), 'auditLog', ['actorUserId'], unique=False)
    op.create_index(op.f('ix_auditLog_createdAt'), 'auditLog', ['createdAt'], unique=False)
    op.create_index(op.f('ix_auditLog_entityId'), 'auditLog', ['entityId'], unique=False)
    op.create_index(op.f('ix_auditLog_organizationId'), 'auditLog', ['organizationId'], unique=False)
    op.create_index(op.f('ix_auditLog_scopeResourceId'), 'auditLog', ['scopeResourceId'], unique=False)
    op.create_index(op.f('ix_auditLog_scopeResourceType'), 'auditLog', ['scopeResourceType'], unique=False)
    op.create_table('userPermissionGrant',
    sa.Column('organizationId', sa.UUID(), nullable=False),
    sa.Column('userId', sa.UUID(), nullable=False),
    sa.Column('permissionId', sa.UUID(), nullable=False),
    sa.Column('effect', sa.String(length=10), nullable=False),
    sa.Column('resourceType', sa.String(length=100), nullable=True),
    sa.Column('resourceId', sa.UUID(), nullable=True),
    sa.Column('origin', sa.String(length=20), nullable=False),
    sa.Column('delegatedFromGrantId', sa.UUID(), nullable=True),
    sa.Column('grantedByUserId', sa.UUID(), nullable=False),
    sa.Column('validFrom', sa.DateTime(timezone=True), nullable=False),
    sa.Column('validUntil', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revokedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auditNote', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['delegatedFromGrantId'], ['userPermissionGrant.id'], ),
    sa.ForeignKeyConstraint(['grantedByUserId'], ['user.id'], ),
    sa.ForeignKeyConstraint(['organizationId'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['permissionId'], ['permission.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment="Grant ou refus individuel d'une permission à un utilisateur, éventuellement scopé à une ressource précise et borné dans le temps (délégation)."
    )
    op.create_index(op.f('ix_userPermissionGrant_delegatedFromGrantId'), 'userPermissionGrant', ['delegatedFromGrantId'], unique=False)
    op.create_index(op.f('ix_userPermissionGrant_organizationId'), 'userPermissionGrant', ['organizationId'], unique=False)
    op.create_index(op.f('ix_userPermissionGrant_permissionId'), 'userPermissionGrant', ['permissionId'], unique=False)
    op.create_index(op.f('ix_userPermissionGrant_userId'), 'userPermissionGrant', ['userId'], unique=False)
    op.create_table_comment(
        'zyloLiquidStationFuelProduct',
        "Association explicite « ce produit est vendu dans cette station » — jamais déduite implicitement d'une cuve existante ou d'un prix déjà saisi (page_configuration.md §15/§41). `active=false` retire le produit de la station sans perdre l'historique de prix déjà enregistré pour ce couple (même philosophie que FuelProduct.active : jamais de suppression réelle d'une donnée référencée ailleurs).",
        existing_comment="Association explicite « ce produit est vendu dans cette station » — jamais déduite implicitement d'une cuve ou d'un prix existant (page_configuration.md §15/§41).",
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'zyloLiquidStationFuelProduct',
        "Association explicite « ce produit est vendu dans cette station » — jamais déduite implicitement d'une cuve ou d'un prix existant (page_configuration.md §15/§41).",
        existing_comment="Association explicite « ce produit est vendu dans cette station » — jamais déduite implicitement d'une cuve existante ou d'un prix déjà saisi (page_configuration.md §15/§41). `active=false` retire le produit de la station sans perdre l'historique de prix déjà enregistré pour ce couple (même philosophie que FuelProduct.active : jamais de suppression réelle d'une donnée référencée ailleurs).",
        schema=None
    )
    op.drop_index(op.f('ix_userPermissionGrant_userId'), table_name='userPermissionGrant')
    op.drop_index(op.f('ix_userPermissionGrant_permissionId'), table_name='userPermissionGrant')
    op.drop_index(op.f('ix_userPermissionGrant_organizationId'), table_name='userPermissionGrant')
    op.drop_index(op.f('ix_userPermissionGrant_delegatedFromGrantId'), table_name='userPermissionGrant')
    op.drop_table('userPermissionGrant')
    op.drop_index(op.f('ix_auditLog_scopeResourceType'), table_name='auditLog')
    op.drop_index(op.f('ix_auditLog_scopeResourceId'), table_name='auditLog')
    op.drop_index(op.f('ix_auditLog_organizationId'), table_name='auditLog')
    op.drop_index(op.f('ix_auditLog_entityId'), table_name='auditLog')
    op.drop_index(op.f('ix_auditLog_createdAt'), table_name='auditLog')
    op.drop_index(op.f('ix_auditLog_actorUserId'), table_name='auditLog')
    op.drop_index(op.f('ix_auditLog_action'), table_name='auditLog')
    op.drop_table('auditLog')
    # ### end Alembic commands ###
