"""billing tables

Revision ID: da0ccc1f6d2c
Revises: 1ede243704c7
Create Date: 2026-08-31 18:03:32.285894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da0ccc1f6d2c'
down_revision: Union[str, None] = '1ede243704c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan',
    sa.Column('moduleCode', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('priceCents', sa.Numeric(precision=12, scale=0), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('periodDays', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['moduleCode'], ['module.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    comment='Offre commerciale pour un module donné (prix, période, fonctionnalités incluses).'
    )
    op.create_index(op.f('ix_plan_moduleCode'), 'plan', ['moduleCode'], unique=False)
    op.create_table('subscription',
    sa.Column('organizationId', sa.UUID(), nullable=False),
    sa.Column('planId', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('startDate', sa.DateTime(timezone=True), nullable=False),
    sa.Column('endDate', sa.DateTime(timezone=True), nullable=False),
    sa.Column('renewedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organizationId'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['planId'], ['plan.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment="Abonnement d'une organisation à un plan — statut trial/active/expired/cancelled."
    )
    op.create_index(op.f('ix_subscription_organizationId'), 'subscription', ['organizationId'], unique=False)
    op.create_index(op.f('ix_subscription_planId'), 'subscription', ['planId'], unique=False)
    op.create_table('invoice',
    sa.Column('subscriptionId', sa.UUID(), nullable=False),
    sa.Column('amountCents', sa.Numeric(precision=12, scale=0), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('issuedAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('paidAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subscriptionId'], ['subscription.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment="Facture émise pour un abonnement — le règlement réel (prestataire de paiement) n'est pas implémenté dans ce socle."
    )
    op.create_index(op.f('ix_invoice_subscriptionId'), 'invoice', ['subscriptionId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoice_subscriptionId'), table_name='invoice')
    op.drop_table('invoice')
    op.drop_index(op.f('ix_subscription_planId'), table_name='subscription')
    op.drop_index(op.f('ix_subscription_organizationId'), table_name='subscription')
    op.drop_table('subscription')
    op.drop_index(op.f('ix_plan_moduleCode'), table_name='plan')
    op.drop_table('plan')
    # ### end Alembic commands ###
