"""leakage_record

Revision ID: f049b4c60e80
Revises: 83f1a725f86b
Create Date: 2026-09-01 12:08:22.118884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f049b4c60e80'
down_revision: Union[str, None] = '83f1a725f86b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zyloLiquidLeakageRecord',
    sa.Column('tankId', sa.UUID(), nullable=False),
    sa.Column('startTime', sa.DateTime(), nullable=False),
    sa.Column('startHeightMm', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('startWaterHeightMm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('startTemperatureC', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('endTime', sa.DateTime(), nullable=False),
    sa.Column('endHeightMm', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('endWaterHeightMm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('endTemperatureC', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('leakRateLph', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('result', sa.String(length=10), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("result IN ('normal','anomaly')", name='ck_zlLeakageRecord_result'),
    sa.ForeignKeyConstraint(['tankId'], ['zyloLiquidTank.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tankId', 'startTime', 'endTime', name='uq_zlLeakageRecord_tank_window'),
    comment="Résultat d'un test de fuite statique — jamais créé manuellement."
    )
    op.create_index(op.f('ix_zyloLiquidLeakageRecord_startTime'), 'zyloLiquidLeakageRecord', ['startTime'], unique=False)
    op.create_index(op.f('ix_zyloLiquidLeakageRecord_tankId'), 'zyloLiquidLeakageRecord', ['tankId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zyloLiquidLeakageRecord_tankId'), table_name='zyloLiquidLeakageRecord')
    op.drop_index(op.f('ix_zyloLiquidLeakageRecord_startTime'), table_name='zyloLiquidLeakageRecord')
    op.drop_table('zyloLiquidLeakageRecord')
    # ### end Alembic commands ###
