"""alert

Revision ID: fb5b32ada7ce
Revises: f049b4c60e80
Create Date: 2026-09-01 12:24:24.804698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb5b32ada7ce'
down_revision: Union[str, None] = 'f049b4c60e80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zyloLiquidAlert',
    sa.Column('tankId', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('triggeredAt', sa.DateTime(), nullable=False),
    sa.Column('triggeredValue', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('thresholdValue', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('resolvedAt', sa.DateTime(), nullable=True),
    sa.Column('resolutionNote', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active','resolved')", name='ck_zlAlert_status'),
    sa.CheckConstraint("type IN ('level_high','level_high_pre_alarm','level_low','water','leak','sensor_offline')", name='ck_zlAlert_type'),
    sa.ForeignKeyConstraint(['tankId'], ['zyloLiquidTank.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Alerte déclenchée automatiquement — résolution manuelle uniquement (sauf sonde déconnectée, point non tranché, Point 2 §4.6).'
    )
    op.create_index(op.f('ix_zyloLiquidAlert_status'), 'zyloLiquidAlert', ['status'], unique=False)
    op.create_index(op.f('ix_zyloLiquidAlert_tankId'), 'zyloLiquidAlert', ['tankId'], unique=False)
    op.create_index(op.f('ix_zyloLiquidAlert_type'), 'zyloLiquidAlert', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zyloLiquidAlert_type'), table_name='zyloLiquidAlert')
    op.drop_index(op.f('ix_zyloLiquidAlert_tankId'), table_name='zyloLiquidAlert')
    op.drop_index(op.f('ix_zyloLiquidAlert_status'), table_name='zyloLiquidAlert')
    op.drop_table('zyloLiquidAlert')
    # ### end Alembic commands ###
