"""fuel_product_thermal_expansion_coefficient

Revision ID: fecaf414f49e
Revises: 82fd37bd908f
Create Date: 2026-09-01 11:04:15.327600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fecaf414f49e'
down_revision: Union[str, None] = '82fd37bd908f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zyloLiquidFuelProduct', sa.Column('thermalExpansionCoefficient', sa.Numeric(precision=8, scale=6), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zyloLiquidFuelProduct', 'thermalExpansionCoefficient')
    # ### end Alembic commands ###
