from app.core.database import AsyncSessionLocal
from app.modules.zylo_liquid.permissions import (
    ALERT_MANAGE,
    ALERT_READ,
    CASH_READ,
    COMMERCIAL_ACCOUNT_MANAGE,
    COMMERCIAL_ACCOUNT_READ,
    DECLARATION_LOCK,
    DOCUMENT_CREATE,
    DOCUMENT_DELETE,
    DOCUMENT_MANAGE,
    DOCUMENT_READ,
    DOCUMENT_READ_SENSITIVE,
    EQUIPMENT_MANAGE,
    EQUIPMENT_READ,
    INTERVENTION_ASSIGN,
    INTERVENTION_CLOSE,
    INTERVENTION_CREATE,
    INTERVENTION_READ,
    PRODUCT_SALE_CANCEL,
    PRODUCT_SALE_CREATE,
    PRODUCT_SALE_READ,
    REGULATORY_DECLARATION_MANAGE,
    REGULATORY_DECLARATION_READ,
    REGULATORY_DOCUMENT_ARCHIVE,
    REGULATORY_DOCUMENT_CREATE,
    REGULATORY_DOCUMENT_MANAGE,
    REGULATORY_DOCUMENT_READ,
    RECONCILIATION_READ,
    RECONCILIATION_SETTINGS_MANAGE,
    SELLABLE_PRODUCT_MANAGE,
    SELLABLE_PRODUCT_READ,
    TECHNICIAN_MANAGE,
    TECHNICIAN_READ,
    DELIVERY_DECLARATION_CREATE,
    DELIVERY_DECLARATION_READ,
    DELIVERY_READ,
    INCIDENT_DECLARATION_CREATE,
    INCIDENT_DECLARATION_READ,
    LEAK_EVENT_READ,
    LEAK_TEST_DECLARATION_CREATE,
    LEAK_TEST_DECLARATION_READ,
    MANUAL_GAUGING_DECLARATION_CREATE,
    MANUAL_GAUGING_DECLARATION_READ,
    PAYMENT_CREATE,
    PAYMENT_READ,
    PRICE_HISTORY_CREATE,
    PRICE_HISTORY_READ,
    QUALITY_CHECK_DECLARATION_CREATE,
    QUALITY_CHECK_DECLARATION_READ,
    RECEIVABLE_MANAGE,
    RECEIVABLE_READ,
    SALE_CREATE,
    SALE_READ,
    SHIFT_CASH_DECLARATION_CREATE,
    SHIFT_CASH_DECLARATION_READ,
    FUEL_PRODUCT_MANAGE,
    FUEL_PRODUCT_READ,
    STATION_FUEL_PRODUCT_MANAGE,
    STATION_FUEL_PRODUCT_READ,
    STATION_MANAGE,
    STATION_READ,
    TANK_MANAGE,
    TANK_READ,
    HOLYKELL_ACCOUNT_READ,
    TANK_CALIBRATION_MANAGE,
    TANK_CALIBRATION_READ,
    TANK_SENSOR_MAPPING_MANAGE,
    TANK_SENSOR_MAPPING_READ,
    CARRIER_READ,
    CARRIER_MANAGE,
    PURCHASE_ORDER_READ,
    PURCHASE_ORDER_MANAGE,
    SUPPLIER_READ,
    SUPPLIER_MANAGE,
    TRUCK_READ,
    TRUCK_MANAGE,
    SECURITY_EQUIPMENT_READ,
    SECURITY_EQUIPMENT_MANAGE,
    STATION_SUPPLIER_READ,
    STATION_SUPPLIER_MANAGE,
    STATION_FINANCIAL_READ,
    STATION_FINANCIAL_MANAGE,
)
from app.rbac.service import get_or_create_permission

# Toute nouvelle permission zylo_liquid doit être ajoutée ici pour être
# accordable — sans quoi `require_permission()` ne trouvera jamais la ligne
# `Permission` correspondante et refusera systématiquement l'accès, y compris
# au owner (Point 3 §14, convention <module>.<ressource>.<action>).
KNOWN_PERMISSIONS = [
    (FUEL_PRODUCT_READ, "Consulter le référentiel des produits carburant."),
    (FUEL_PRODUCT_MANAGE, "Créer/modifier le référentiel des produits carburant."),
    (STATION_FUEL_PRODUCT_READ, "Consulter les produits associés à une station."),
    (STATION_FUEL_PRODUCT_MANAGE, "Associer/retirer un produit d'une station."),
    (STATION_READ, "Consulter les stations de l'organisation."),
    (STATION_MANAGE, "Créer/modifier/activer/désactiver les stations de l'organisation."),
    (TANK_READ, "Consulter les cuves des stations de l'organisation."),
    (TANK_MANAGE, "Créer/modifier les cuves des stations de l'organisation."),
    (TANK_SENSOR_MAPPING_READ, "Consulter les associations capteur-cuve."),
    (TANK_SENSOR_MAPPING_MANAGE, "Créer/clore les associations capteur-cuve."),
    (TANK_CALIBRATION_READ, "Consulter la table de calibration d'une cuve."),
    (TANK_CALIBRATION_MANAGE, "Charger (remplacer) la table de calibration d'une cuve."),
    (HOLYKELL_ACCOUNT_READ, "Consulter l'état de synchronisation d'un compte Holykell."),
    (DELIVERY_READ, "Consulter les livraisons détectées."),
    (LEAK_EVENT_READ, "Consulter les événements de fuite détectés."),
    (ALERT_READ, "Consulter les alertes."),
    (ALERT_MANAGE, "Résoudre une alerte."),
    (PRICE_HISTORY_READ, "Consulter l'historique des prix."),
    (PRICE_HISTORY_CREATE, "Enregistrer un changement réel de prix ou corriger un prix historique."),
    (CASH_READ, "Consulter la caisse (ventes estimées à partir de la télémétrie)."),
    (DELIVERY_DECLARATION_READ, "Consulter les livraisons déclarées."),
    (DELIVERY_DECLARATION_CREATE, "Déclarer une livraison ou corriger une déclaration existante."),
    (SHIFT_CASH_DECLARATION_READ, "Consulter les déclarations de prise/fin de poste et caisse."),
    (SHIFT_CASH_DECLARATION_CREATE, "Déclarer une prise/fin de poste et caisse."),
    (MANUAL_GAUGING_DECLARATION_READ, "Consulter les jaugeages manuels déclarés."),
    (MANUAL_GAUGING_DECLARATION_CREATE, "Déclarer un jaugeage manuel de contrôle."),
    (QUALITY_CHECK_DECLARATION_READ, "Consulter les contrôles qualité/eau déclarés."),
    (QUALITY_CHECK_DECLARATION_CREATE, "Déclarer un contrôle qualité/eau."),
    (LEAK_TEST_DECLARATION_READ, "Consulter les tests de fuite déclenchés manuellement."),
    (LEAK_TEST_DECLARATION_CREATE, "Déclarer le résultat d'un test de fuite déclenché manuellement."),
    (INCIDENT_DECLARATION_READ, "Consulter les incidents/observations déclarés."),
    (INCIDENT_DECLARATION_CREATE, "Déclarer un incident ou une observation libre."),
    (DECLARATION_LOCK, "Verrouiller une déclaration (rapprochement ou validation), quel que soit son type."),
    (COMMERCIAL_ACCOUNT_READ, "Consulter les comptes clients à crédit."),
    (COMMERCIAL_ACCOUNT_MANAGE, "Créer/modifier un compte client à crédit, ses véhicules, conducteurs et autorisations."),
    (SALE_READ, "Consulter les ventes."),
    (SALE_CREATE, "Enregistrer une vente."),
    (RECEIVABLE_READ, "Consulter les créances clients."),
    (RECEIVABLE_MANAGE, "Ajuster manuellement une créance."),
    (PAYMENT_READ, "Consulter les paiements."),
    (PAYMENT_CREATE, "Enregistrer un paiement, réduisant une créance."),
    (DOCUMENT_READ, "Consulter les documents et leurs liaisons."),
    (DOCUMENT_CREATE, "Référencer un document et le lier à une ou plusieurs entités."),
    (RECONCILIATION_READ, "Consulter les résultats de rapprochement."),
    (RECONCILIATION_SETTINGS_MANAGE, "Configurer les tolérances de rapprochement d'une station."),
    # Mission « vente-maintenant-reglementation » (06-permissions-par-domaine.md
    # de la mission) — permissions par domaine ajoutées après l'activation
    # initiale du module par des organisations existantes : couvertes par
    # `backfill_active_module_permissions_for_owners` au prochain démarrage.
    (DOCUMENT_MANAGE, "Remplacer un document par une nouvelle version."),
    (DOCUMENT_DELETE, "Supprimer (logiquement) un document."),
    (DOCUMENT_READ_SENSITIVE, "Consulter un document marqué 'restreint'."),
    (SELLABLE_PRODUCT_READ, "Consulter le catalogue de produits vendables (boutique)."),
    (SELLABLE_PRODUCT_MANAGE, "Créer/modifier/importer des produits vendables (boutique)."),
    (PRODUCT_SALE_READ, "Consulter les ventes de produits boutique."),
    (PRODUCT_SALE_CREATE, "Enregistrer une vente de produit(s) boutique."),
    (PRODUCT_SALE_CANCEL, "Annuler une vente de produit(s) boutique déjà validée."),
    (EQUIPMENT_READ, "Consulter les équipements des stations."),
    (EQUIPMENT_MANAGE, "Créer/modifier les équipements des stations."),
    (INTERVENTION_READ, "Consulter les interventions de maintenance."),
    (INTERVENTION_CREATE, "Signaler/créer une intervention de maintenance."),
    (INTERVENTION_ASSIGN, "Affecter un technicien à une intervention."),
    (INTERVENTION_CLOSE, "Clôturer une intervention de maintenance."),
    (TECHNICIAN_READ, "Consulter les techniciens de maintenance."),
    (TECHNICIAN_MANAGE, "Créer/modifier les techniciens de maintenance."),
    (REGULATORY_DOCUMENT_READ, "Consulter les documents réglementaires des stations."),
    (REGULATORY_DOCUMENT_CREATE, "Ajouter un document réglementaire."),
    (REGULATORY_DOCUMENT_MANAGE, "Modifier/renouveler un document réglementaire."),
    (REGULATORY_DOCUMENT_ARCHIVE, "Archiver un document réglementaire."),
    (REGULATORY_DECLARATION_READ, "Consulter les déclarations réglementaires des stations."),
    (REGULATORY_DECLARATION_MANAGE, "Créer/modifier une déclaration réglementaire."),
    # Couche Approvisionnement — fusion de la page prototype #/livraisons
    # (décision commanditaire « créer toutes les tables nécessaires, même
    # fournisseur ») : permissions ajoutées après l'activation initiale du
    # module par des organisations existantes — couvertes par
    # `backfill_active_module_permissions_for_owners` au prochain démarrage
    # (même mécanisme que le bloc « vente-maintenant-reglementation »
    # ci-dessus). Codes owner-only (aucun rôle par défaut ne les porte) :
    # sans ce registre, aucune ligne Permission n'existerait jamais et le
    # grant au owner ne pourrait rien accorder.
    (SUPPLIER_READ, "Consulter le référentiel des fournisseurs."),
    (SUPPLIER_MANAGE, "Créer/modifier le référentiel des fournisseurs."),
    (CARRIER_READ, "Consulter le référentiel des transporteurs."),
    (CARRIER_MANAGE, "Créer/modifier le référentiel des transporteurs."),
    (TRUCK_READ, "Consulter le référentiel des camions."),
    (TRUCK_MANAGE, "Créer/modifier le référentiel des camions."),
    (PURCHASE_ORDER_READ, "Consulter les commandes d'approvisionnement."),
    (PURCHASE_ORDER_MANAGE, "Créer/modifier les commandes d'approvisionnement."),
    # Centre administratif et opérationnel de la station — domaines Sécurité,
    # Fournisseurs (par station) et Finances, ajoutés après l'activation
    # initiale du module par des organisations existantes — couverts par
    # `backfill_active_module_permissions_for_owners` au prochain démarrage.
    (SECURITY_EQUIPMENT_READ, "Consulter les équipements de sécurité incendie/ATEX d'une station."),
    (SECURITY_EQUIPMENT_MANAGE, "Créer/modifier les équipements de sécurité incendie/ATEX d'une station."),
    (STATION_SUPPLIER_READ, "Consulter les fournisseurs associés à une station."),
    (STATION_SUPPLIER_MANAGE, "Associer/retirer un fournisseur d'une station."),
    (STATION_FINANCIAL_READ, "Consulter les informations administratives/fiscales d'une station, y compris les coordonnées bancaires."),
    (STATION_FINANCIAL_MANAGE, "Modifier les informations administratives/fiscales d'une station."),
]


async def seed_known_permissions() -> None:
    async with AsyncSessionLocal() as db:
        for code, description in KNOWN_PERMISSIONS:
            await get_or_create_permission(db, code, "zylo_liquid", description)
        await db.commit()
